var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                        x                                                       ",
   "                        x                                                       ",
   "                      xxxxx                         x                           ",
   "                       xxx                          x                           ",
   "                        x                           x                           ",
   "                                    o o             x                           ",
   "                        s                   xxxx    x                           ",
   "                     xxxxxxxxxxxxxxxxxxx            x                           ",
   "                     x           v                 xxx                   f   x  ",
   "  x                  x                     o o     xxv                       x  ",
   "  x                  x   o                       xxxx              o         x  ",
   "  x                  x                    xxxxx!!                            x  ",
   "  x                         xxx                             o                x  ",
   "  x  @       xxx            xxx        o o o                     xxxxx   w   x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   ["  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
    "  x                                                                          x  ",
    "  x    @       o o o                                                         x  ",
    "  x                                   o o                                    x  ",
    "  x                                                            y         o   x  ",
    "  xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxx!!!xxxxxxxx     xxxxxxxx  xxxxxxxxx  ",
    "  x                        xxx               !!!xxxxxx  o  xxxxxxxx!!xxxxxxxxx  ",
    "  x                                                xxx  o  xxxxxxxxxxxxxxxxxxx  ",
    "  x                                                       xx                 x  ",
    "  x                       o                                x           f     x  ",
    "  x                      xxx   o o                      y  x                 x  ",
    "  x                   yxxx xxxxxxxxxxxx    o o  xxxxxxxxxxxx                 x  ",
    "  x             xxxxxxxx               xxxxxxxxxxxx      v                   x  ",
    "  x                                                                          x  ",
    "  x      o                                                                   x  ",
    "  x   o o o o      o                    s                          w         x  ",
    "  x y    o                 y         xxxxxxxxxxx!!xxxx       o o xxxxxx  o o x  ",
    "  xxxxxxxxxxxx   xxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx    xxxxxxxx  ",
    "              !!!             x   x                  x     x                    ",
    "                              x!!!x                  x!!!!!x                    ",
    "                              x!!!x                  x!!!!!x                    ",
    "                              xxxxx                  xxxxxxx                    ",
    "                                                                                ",
    "                                                                                "],
   ["                    x             x                       x                                                                 ",
    "                    x             x                       x                                                                 ",
    "                    x     o       x                       x                                                                 ",
    " x                  x             x                       x                                                                 ",
    " x                  x     x       x                       x                                                                 ",
    " x    @        o    x    xxx      x                       x                                                                 ",
    " x                  x     x       x                       x                                                                 ",
    " xxxxxxxxxxx        x     x   =   x   o                   x                                                                 ",
    "          x   o    !xx    x       x o o o                 x                                                                 ",
    "         x        !v      x       x   o                 s x                                                                 ",
    " xxxxxxxx        !      o x   =   xxxxxxxxx         xxxxxxxxxxx                                                             ",
    " x    v     o   !       xxx                        x          x                                                             ",
    " x              !!       x    o                   y           x                                                             ",
    " x             !!!!xx     xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!xxx                                                             ",
    " x             !          x                    x         |            x                                                     ",
    " x         xxx !        x x                    x                      x          o      xxxxxx   !        !                 ",
    " x                        x                    x  f                   x                   x      !        !                 ",
    " x    o                y  x                    x                      x         xxx       x      !        !                 ",
    " xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 x              xxx     x                   x      !        !                 ",
    "                                               x        xxx           x                xxx       !   o    !                 ",
    "                                               xxxxxx               xxx             xxx              w                      ",
    "                                               x                   x            yxxx                xxxx                    ",
    "                                               x                         xxxxxx                                             ",
    "                                               x                         x                                                  ",
    "                                               x              xxxxxxxxxxxx                                                  ",
    "                                               !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
    ["                                                                                                                           ",
     "                                                                                                                           ",
     "                                                                                                                           ",
     "                     f                                                                                                     ",
     "                                                                                                                           ",
     "        x     x      o                                                                                                     ",
     "         x   x      xxx      x     x             v                                                                         ",
     "          x x     xx   xx    x     x                                                                                       ",
     "           x     x       x   x     x                                                                                       ",
     "           x      xx   xx     x   x                                                                                        ",
     "           x        xxx        xxx                                                                                         ",
     "                                                                                                                           ",
     "       x           x   x     xxxxx                                                                                         ",
     "        x         x         x     x                                                                                        ",
     "         x   x   x     x   x       x                                                                                       ",
     "          x x x x      x   x       x                    x                                                                  ",
     "           x   x       x   x       x                    x                                                                  ",
     "  x                                                     x                                                                  ",
     "  x                                                   o x                                                                  ",
     "  x    @                                              o x                                                                  ",
     "  xs                                 y         w      o x                                                                  ",
     "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxx                                                                  ",
     "                                                                                                                           ",
     "                                                                                                                           ",
     "                                                                                                                           ",
     "                                                                                                                           "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
